### ISSUE TITLE
不能更新滴呀

### ISSUE THREAD

**Issue by ghost** [WindFgg/kingfeng#1]
退出登录后重登，看去变量一堆重复的
![Screenshot_2021-09-11-06-05-06-38_11d59881ebb69c15251b128bef75a7ea](https://user-images.githubusercontent.com/40169265/132922648-8680e78a-a343-41d6-a1a7-251c2a68f383.jpg)

**Comment by windfgg** [comment]
删除配置文件 重新部署填写配置即可 上面出现的重复问题没遇到过
