### ISSUE TITLE
可不可以搞成容器内部更新？

### ISSUE THREAD

**Issue by WindStill** [WindFgg/kingfeng#2]
可不可以搞成容器内部更新？像青龙和Ninja一样内部拉取代码更新。你这个删容器、创建容器动作有点大啊😂

**Comment by QiFengg** [comment]
@WindStill 特性

**Comment by windfgg** [comment]
@WindStill 特性 单容器部署 无侵入

**Comment by WindStill** [comment]
我意思是在kingfeng容器内更新代码，不是青龙的容器

**Comment by windfgg** [comment]
@WindStill 其实文档已经写了 部署方式不限 只提供一种
授人以鱼不如授人以渔

**Comment by WindStill** [comment]
这样你也不用维护docker镜像的版本了，只要维护代码即可。

**Comment by WindStill** [comment]
> @WindStill 其实文档已经写了 部署方式不限 只提供一种
> 授人以鱼不如授人以渔

好吧。

**Comment by windfgg** [comment]
@WindStill 看使用人数解决 我懒

**Comment by WindStill** [comment]
本来想按照你的dockerfile搞搞的，结果发现是dotnet，实在不熟。
或者能把编译、部署流程说下也行。

**Comment by windfgg** [comment]
@WindStill fork gitaction 自动构建 这个目前上手最快
