### ISSUE TITLE
关于MaxCount参数的问题

### ISSUE THREAD

**Issue by trytrytogo** [WindFgg/kingfeng#4]
首先，感谢您开发这个工具，对于多容器管理有很大的帮助！

目前，我刚装了一套测试了一下，发现有2个情况，不确定是bug还是设计之初就是这样的。
1：节点不显示允许总共CK数量或者剩余可用的CK数量；
2：在1个节点满了之后，例如我想更新CK,发现这个节点已经是灰色了，无法选择节点，来重新提交CK来更新。

我也去您的频道找了，也没有找到相关的入口，特来请教！

最后再次感谢您开发这个管理工具。

**Comment by windfgg** [comment]
@ixinshang 你好,本程序开发的初衷就是自己使用,确实会有一些逻辑或者其他方面的Bug 本人并无精力去完善修改这些bug 如有需要可以自己修改 MIT协议可以随便传播修改保存版权即可  由于是第一次使用这些技术  写的也很烂  也并没计划去重构逻辑

**Comment by windfgg** [comment]
@ixinshang 管理员登录直接随便选择节点输入管理员密钥即可登录

**Comment by trytrytogo** [comment]
已经找到3的

> @ixinshang 管理员登录直接随便选择节点输入管理员密钥即可登录

感谢您的回复。   目前已解决SecretKey 用法的情况。
